package:
  name: aws-cli
  version: 1.27.164
  epoch: 1
  description: "Universal Command Line Interface for Amazon Web Services"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-setuptools
      - py3-yaml
      - py3-botocore
      - py3-docutils
      - py3-jmespath
      - py3-rsa
      - py3-s3transfer
      - py3-colorama
      - groff

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - python3-dev
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/aws/aws-cli/archive/${{package.version}}.tar.gz
      expected-sha256: d92c97189720024c2c618cd9e15ae3408183bcde64ac94af764dac8073e1d822

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: aws/aws-cli
    use-tag: true
    tag-filter: "1.27"
