package:
  name: conda
  version: 23.7.2
  epoch: 2
  description: "A system-level, binary package and environment manager running on all major operating systems and platforms."
  copyright:
    - license: BSD-3-Clause
  options:
    no-provides: true
    no-depends: true
  dependencies:
    runtime:
      - python3
      - py3-packaging

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - bash
      - wget
      - python3
      - py3-pip
      - py3-hatchling
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/conda/conda
      tag: ${{package.version}}
      expected-commit: b63f152aaf78a014afab66ee48eae663cf563cd6

  - runs: |
      pip install hatch
      hatch build
      python3 -m installer -d "${{targets.destdir}}" dist/conda*.whl

update:
  enabled: true
  github:
    identifier: conda/conda
