package:
  name: cri-tools
  version: 1.27.0
  epoch: 0
  description: CLI and validation tools for Kubelet Container Runtime Interface (CRI) .
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/cri-tools
      tag: v${{package.version}}
      expected-commit: b60f39bc21df6988e2e0c7a9cd041802b1473ec2

  - uses: go/build
    with:
      packages: ./cmd/crictl
      output: crictl
      ldflags: -s -w -X github.com/kubernetes-sigs/cri-tools/pkg/version.VERSION=${{package.version}}

  - runs: |
      make critest
      install -Dm755 build/bin/linux/**/critest "${{targets.destdir}}"/usr/bin/critest

  - uses: strip

subpackages:
  - name: "crictl"
    description: "CLI for kubelet CRI"
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/crictl ${{targets.subpkgdir}}/usr/bin/crictl

  - name: "critest"
    description: "validation test suites for kubelet CRI"
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/critest ${{targets.subpkgdir}}/usr/bin/critest

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cri-tools
    strip-prefix: v
