package:
  name: erlang-25
  version: 25.3.2.3
  epoch: 1
  description: General-purpose programming language and runtime environment
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      # mnesia depends on the ca-certificates bundle
      - ca-certificates-bundle
    provides:
      - erlang=25.3.2.2

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - perl-dev
      - openssl-dev
      - ncurses-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8c1e8811201d1e9cc806b74393db16e89a119f412e16bb5f6181d54cd102eb4f
      uri: https://github.com/erlang/otp/releases/download/OTP-${{package.version}}/otp_src_${{package.version}}.tar.gz

  - runs: |
      export CPPFLAGS="-D_BSD_SOURCE $CPPFLAGS"

      ./otp_build autoconf
      ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --host="$CHOST" \
        --build="$CBUILD" \
        --enable-threads \
        --enable-shared-zlib \
        --enable-ssl=dynamic-ssl-lib \
        --enable-jit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "erlang-25-dev"
    description: "headers for erlang"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - erlang
      provides:
        - erlang-dev=25.3.2.2

update:
  enabled: true
  github:
    identifier: erlang/otp
    strip-prefix: OTP-
    use-tag: true
    tag-filter: OTP-25
