package:
  name: external-secrets-operator
  version: 0.8.3
  epoch: 3
  description: Integrate external secret management systems with Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - git
      - bash
      - go
      - yq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/external-secrets/external-secrets
      tag: v${{package.version}}
      expected-commit: d34981a228d4e66bde08d33a6b62ca808594a059

  - runs: |
      go get github.com/lestrrat-go/jwx@v1.2.26
      go mod tidy
      make build-$(go env GOARCH)
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 -D bin/external-secrets-$(go env GOOS)-$(go env GOARCH) "${{targets.destdir}}"/usr/bin/external-secrets

  - uses: strip

update:
  enabled: true
  github:
    identifier: external-secrets/external-secrets
    strip-prefix: v
    tag-filter: v
