package:
  name: ffmpeg
  version: 6.0
  epoch: 1
  description: ffmpeg multimedia library
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - yasm
      - x264-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.ffmpeg.org/ffmpeg.git
      expected-commit: ea3d24bbe3c58b171e55fe2151fc7ffaca3ab3d2
      tag: n${{package.version}}
      depth: 1

  - runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --enable-shared \
        --enable-libx264 \
        --enable-gpl

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

data:
  - name: libraries
    items:
      libavcodec60: libavcodec
      libavdevice60: libavdevice
      libavfilter9: libavfilter
      libavformat60: libavformat
      libavutil58: libavutil
      libswresample4: libswresample
      libswscale7: libswscale

subpackages:
  - range: libraries
    name: ${{range.key}}
    description: "${{range.value}} library"
    pipeline:
      - runs: |
          # CHECK-WHEN-VERSION-CHANGES: 6.0
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/${{range.value}}.so.*.* "${{targets.subpkgdir}}"/usr/lib/

  - name: ffmpeg-static
    pipeline:
      - uses: split/static
    description: ffmpeg static libraries

  - name: ffmpeg-dev
    pipeline:
      - uses: split/dev
    description: ffmpeg development headers

  - name: ffmpeg-doc
    pipeline:
      - uses: split/manpages
    description: ffmpeg manpages

update:
  enabled: true
  release-monitor:
    identifier: 5405
