package:
  name: freerdp
  version: 2.10.0
  epoch: 0
  description: FreeRDP client
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - ca-certificates-bundle
      - busybox
      - alsa-lib-dev
      # - bsd-compat-headers
      - cmake
      - cups-dev
      - gsm-dev
      - gst-plugins-base-dev
      - libjpeg-turbo-dev
      - libusb-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-dev
      # - libxkbfile-dev
      - libxkb-dev
      - libxv-dev
      - linux-headers
      - openssl-dev>3
      - samurai
      - libxext-dev
      - libx11-dev
      - libxrender-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/FreeRDP/FreeRDP/archive/${{package.version}}.tar.gz
      expected-sha512: 388c00d2f883b41d4ec127bcb871607429c136bfb99daf87f491e9f1e7d456e1fac403db9f9dec7611e729dfd2f913fa414ed3d0020d92c284c8f3ba1eeb80cb

  - runs: |
      CFLAGS="$CFLAGS -fPIC" \
      CXXFLAGS="$CXXFLAGS -fPIC" \
      cmake -B build -G Ninja \
      	-DCMAKE_BUILD_TYPE=MinSizeRel \
      	-DCMAKE_INSTALL_PREFIX=/usr \
      	-DCMAKE_INSTALL_LIBDIR=lib \
      	-DWITH_ALSA=ON \
      	-DWITH_CUPS=ON \
      	-DWITH_CHANNELS=ON \
      	-DBUILTIN_CHANNELS=OFF \
      	-DWITH_DIRECTFB=OFF \
      	-DWITH_FFMPEG=OFF \
      	-DWITH_GSM=ON \
      	-DWITH_GSTREAMER_1_0=ON \
      	-DWITH_IPP=OFF \
      	-DWITH_JPEG=ON \
      	-DWITH_OPENSSL=ON \
      	-DWITH_PCSC=OFF \
      	-DWITH_PULSE=OFF \
      	-DWITH_WAYLAND=ON \
      	-DWITH_SERVER=ON \
      	-DWITH_X11=ON \
      	-DWITH_XCURSOR=ON \
      	-DWITH_XEXT=ON \
      	-DWITH_XKBFILE=ON \
      	-DWITH_XI=ON \
      	-DWITH_XINERAMA=ON \
      	-DWITH_XRENDER=ON \
      	-DWITH_XV=ON \
      	-DWITH_ZLIB=ON \
      	-DWITH_NEON=OFF
       cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: freerdp-doc
    description: freerdp man pages
    pipeline:
      - uses: split/manpages

  - name: freerdp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - freerdp
    description: freerdp dev

  - name: freerdp-libs
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/* ${{targets.subpkgdir}}/usr/lib
    description: freerdp library

update:
  enabled: true
  release-monitor:
    identifier: 10442
