package:
  name: freetype
  version: 2.13.1
  epoch: 0
  description: TrueType font rendering library
  copyright:
    - license: FTL GPL-2.0-or-later

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - brotli-dev
      - bzip2-dev
      - libpng-dev
      - libx11-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: ea67e3b019b1104d1667aa274f5dc307d8cbd606b399bc32df308a77f1a564bf
      uri: https://download.savannah.gnu.org/releases/freetype/freetype-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --enable-static \
        --with-brotli \
        --with-bzip2 \
        --with-png \
        --enable-freetype-config

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: freetype-static
    description: freetype static library
    pipeline:
      - uses: split/static

  - name: freetype-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - freetype
        - libx11-dev
        - libpng-dev
        - bzip2-dev
        - brotli-dev
    description: freetype dev

  - name: freetype-doc
    pipeline:
      - uses: split/manpages
    description: freetype manpages

update:
  enabled: true
  release-monitor:
    identifier: 854
