package:
  name: fuse-overlayfs-snapshotter
  version: 1.0.6
  epoch: 0
  description: fuse-overlayfs plugin for rootless containerd
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - fuse-overlayfs

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - go
      - fuse3-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containerd/fuse-overlayfs-snapshotter
      expected-commit: a705ae6f22850358821ec1e7d968bc79003934ef
      tag: v${{package.version}}

  - runs: |
      make bin/containerd-fuse-overlayfs-grpc

      make install BINDIR="${{targets.destdir}}"/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: containerd/fuse-overlayfs-snapshotter
    strip-prefix: v
