package:
  name: fuse-overlayfs
  version: 1.12
  epoch: 0
  description: FUSE implementation for overlayfs
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      # TODO: Provide a static build option as well
      - fuse3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - linux-headers
      - fuse3-dev
      - automake
      - autoconf
      - libtool
      - pkgconf-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/fuse-overlayfs
      expected-commit: 560ab7d9de5c1de115dda75fcd9420c59beeee37
      tag: v${{package.version}}

  - name: Run autoreconf
    runs: |
      ./autogen.sh

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: containers/fuse-overlayfs
    strip-prefix: v
