package:
  name: gst-plugins-base
  version: 1.22.4
  epoch: 1
  description: GStreamer streaming media framework base plug-ins
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - alsa-lib-dev
      - cdparanoia-dev
      - expat-dev
      - glib-dev
      - gobject-introspection-dev
      - graphene-dev
      - gstreamer-dev
      - gtk-2.0-dev
      - libice-dev
      - libogg-dev
      - libsm-dev
      - libtheora-dev
      - libvorbis-dev
      - libxv-dev
      - mesa-dev
      - meson
      - opus-dev
      - orc-compiler
      - orc-dev
      - perl
      - cmake
      - gdk-pixbuf
      - gstreamer

pipeline:
  - uses: fetch
    with:
      expected-sha512: f623a78534ec7674e770bbec3900f909efd2b3388cfa5d3c47cceb968acbad681ba1b1fa1925f82c21f17151c226d9b5f188fc8699a57f2a94329d18d5745639
      uri: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${{package.version}}.tar.xz

  - runs: |
      # This breaks the build on aarc64 builds
      if [ "${{build.arch}}" = "aarch64" ]; then
        export LDFLAGS="$(echo $LDFLAGS | sed 's/,-z,noexecheap//g')"
      fi
      meson \
        --prefix=/usr \
      	-Dalsa=enabled \
      	-Dintrospection=enabled \
        -Dtests=disabled \
      	. output
      meson compile -C output

      DESTDIR="${{targets.destdir}}" meson install --no-rebuild -C output

  - uses: strip

subpackages:
  - name: gst-plugins-base-dev
    pipeline:
      - uses: split/dev
    description: gst-plugins-base dev

  - name: gst-plugins-base-doc
    pipeline:
      - uses: split/manpages
    description: gst-plugins-base manpages

  - name: gst-plugins-base-lang
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/locale
          mv ${{targets.destdir}}/usr/share/locale ${{targets.subpkgdir}}/usr/share/locale
    description: gst-plugins-base lang

update:
  enabled: true
  release-monitor:
    identifier: 21850
