package:
  name: guacamole-server
  version: 1.5.2
  epoch: 2
  description: clientless remote desktop gateway server
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - libjpeg-turbo-dev
      - cairo-dev
      - automake
      - libpng-dev
      - libtelnet
      - libvncserver-dev
      - util-linux-dev
      - pango-dev
      - perl
      - openssl-dev
      - libwebp-dev
      - ffmpeg-dev
      - curl
      - libswresample4
      - harfbuzz-dev
      - expat-dev
      - libxft-dev
      - fribidi-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: a8d4813feaeb1e6f35fbfd2cf57cb0429db2225960cbfed36252f65ac93dffc4
      uri: https://apache.org/dyn/closer.lua/guacamole/${{package.version}}/source/guacamole-server-${{package.version}}.tar.gz?action=download

  - runs: |
      CFLAGS="$CFLAGS -Wno-error" ./configure \
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --with-pango \
        --with-vnc \
        --with-telnet

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: guacamole-server-doc
    description: guacamole-server documentation
    pipeline:
      - uses: split/manpages

  - name: guacamole-server-dev
    description: guacamole-server development files
    pipeline:
      - uses: split/dev

  - name: libguac-client-vnc
    description: guacamole-server VNC client plugin
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libguac-client-vnc.so.* ${{targets.subpkgdir}}/usr/lib/

  - name: libguac-client-telnet
    description: guacamole-server Telnet client plugin
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libguac-client-telnet.so.* ${{targets.subpkgdir}}/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 141451
