package:
  name: jenkins
  version: "2.412"
  epoch: 0
  description:
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ttf-dejavu

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - coreutils
      - bash
      - openssh-client
      - tini
      - openjdk-17
      - openjdk-17-default-jvm
      - maven
      - tzdata
      - glibc-locale-en
      - git
      - patch
      - ttf-dejavu

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/jenkinsci/jenkins/archive/refs/tags/jenkins-${{package.version}}.tar.gz
      expected-sha256: 7cb0e6da9f27ee92e4cef133c0a861dd9ca46263f8655c6114c03f00d58825d8

  - uses: patch
    with:
      patches: ignoreArchiveNotReadableTest.patch

  - runs: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      export LANG=en_US.UTF-8

      export MAVEN_OPTS="-DforkCount=2"

      # tests take ~1.5 hours to run and have passed 100% since the initial addition of Jenkins, let's skip them and save time + resources
      mvn install -DskipTests=true

      mkdir -p ${{targets.destdir}}/usr/share/java/jenkins
      mv war/target/jenkins.war ${{targets.destdir}}/usr/share/java/jenkins/

update:
  enabled: true
  github:
    identifier: jenkinsci/jenkins
    strip-prefix: jenkins-
