package:
  name: keycloak
  version: 21.1.2
  epoch: 0
  description:
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation:
      license: Apache-2.0
  dependencies:
    runtime:
      - bash # some helper scripts use bash
      - openjdk-17-default-jvm

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
      - bash
      - nodejs-16
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/keycloak/keycloak
      tag: ${{package.version}}
      expected-commit: 99774b3f7a776476e7f04e472e13e3915971a6fb

  - runs: |
      export LANG=en_US.UTF-8
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk

      mvn install -DskipTests=true -Dnode.version=$(node --version) -Pdistribution -q

      mkdir -p ${{targets.destdir}}/usr/share/java
      unzip -d ${{targets.destdir}}/usr/share/java quarkus/dist/target/keycloak-*.zip

      mkdir -p ${{targets.destdir}}/usr/bin
      for i in kc.sh kcadm.sh kcreg.sh; do
        ln -sf /usr/share/java/keycloak-${{package.version}}/bin/$i ${{targets.destdir}}/usr/bin/$i
      done

update:
  enabled: true
  github:
    identifier: keycloak/keycloak
    use-tag: true
    # There are a lot of older minor versions and tag schemes that make this flaky, restrict to just this major version
    tag-filter: "21."
