package:
  name: krb5
  version: 1.21
  epoch: 0
  description: The Kerberos network authentication system
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - e2fsprogs-dev
      - libverto-dev
      - openldap-dev
      - openssl-dev
      - keyutils-dev
      - bison
      - flex
      - perl
      - krb5-conf

pipeline:
  - uses: fetch
    with:
      expected-sha256: 69f8aaff85484832df67a4bbacd99b9259bd95aab8c651fbbe65cdc9620ea93b
      uri: https://web.mit.edu/kerberos/dist/krb5/1.21/krb5-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      dir: src
      opts: |
        CPPFLAGS="$CPPFLAGS -fPIC -I/usr/include/et" \
        --localstatedir=/var/lib \
        --enable-shared \
        --disable-nls \
        --disable-static \
        --disable-rpath \
        --with-system-et \
        --with-system-ss \
        --with-system-verto \
        --without-tcl \
        --with-ldap

  - uses: autoconf/make
    with:
      dir: src

  - uses: autoconf/make-install
    with:
      dir: src

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/doc/krb5
      mv ${{targets.destdir}}/usr/share/examples ${{targets.destdir}}/usr/share/doc/krb5/

  - uses: strip

subpackages:
  - name: krb5-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - krb5-libs
        - e2fsprogs-dev
        - libverto-dev
        - krb5-conf
    description: krb5 dev

  - name: krb5-doc
    pipeline:
      - uses: split/manpages
    description: krb5 manpages

  - name: krb5-server
    dependencies:
      runtime:
        - libverto-libev
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share
          mkdir -p ${{targets.subpkgdir}}/usr/bin

          install -d ${{targets.subpkgdir}}/var/lib/krb5kdc
          mv ${{targets.destdir}}/usr/sbin ${{targets.subpkgdir}}/usr/

          mv ${{targets.destdir}}/usr/bin/sclient ${{targets.subpkgdir}}/usr/bin/
    description: The KDC and related programs for Kerberos 5

  - name: krb5-server-ldap
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/krb5/plugins/kdb
          mkdir -p ${{targets.subpkgdir}}/usr/lib

          install -Dm644 \
            -t ${{targets.subpkgdir}}/usr/share/kerberos \
            src/plugins/kdb/ldap/libkdb_ldap/kerberos.ldif \
            src/plugins/kdb/ldap/libkdb_ldap/kerberos.openldap.ldif

          mv ${{targets.destdir}}/usr/lib/krb5/plugins/kdb/kldap.so ${{targets.subpkgdir}}/usr/lib/krb5/plugins/kdb/
          mv ${{targets.destdir}}/usr/lib/libkdb_ldap* ${{targets.subpkgdir}}/usr/lib/
    description: The LDAP storage plugin for the Kerberos 5 KDC

  - name: krb5-pkinit
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/krb5/plugins/preauth
          mv ${{targets.destdir}}/usr/lib/krb5/plugins/preauth/pkinit.so ${{targets.subpkgdir}}/usr/lib/krb5/plugins/preauth/
    description: The PKINIT module for Kerberos 5

  - name: krb5-libs
    dependencies:
      runtime:
        - krb5-conf
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib ${{targets.subpkgdir}}/usr/
    description: The shared libraries used by Kerberos 5

update:
  enabled: true
  release-monitor:
    identifier: 13287
    strip-suffix: -final
