package:
  name: libvncserver
  version: 0.9.14
  epoch: 1
  description: Library to make writing a vnc server easy
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - cmake
      - ninja
      - build-base
      - libgcrypt-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libice-dev
      - libx11-dev
      - libxdamage-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxtst-dev
      - openssl-dev
      - lzo-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/LibVNC/libvncserver/archive/LibVNCServer-${{package.version}}.tar.gz
      expected-sha256: 83104e4f7e28b02f8bf6b010d69b626fae591f887e949816305daebae527c9a5

  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=ON \
        -DWITH_ZLIB=ON \
        -DWITH_LZO=ON \
        -DWITH_JPEG=ON \
        -DWITH_PNG=ON \
        -DWITH_SDL=ON \
        -DWITH_THREADS=ON \
        -DWITH_GNUTLS=ON \
        -DWITH_OPENSSL=ON \
        -DWITH_SYSTEMD=OFF \
        -DWITH_GCRYPT=ON \
        -DWITH_FFMPEG=ON \
        -DWITH_WEBSOCKETS=ON \
        -DWITH_SASL=ON
      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: libvncserver-dev
    pipeline:
      - uses: split/dev
    description: libvncserver dev

update:
  enabled: true
  github:
    identifier: LibVNC/libvncserver
    strip-prefix: LibVNCServer-
    use-tag: true
    tag-filter: LibVNCServer-
