package:
  name: libwebp
  version: 1.3.0
  epoch: 1
  description: Libraries for working with WebP images
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - giflib-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libtool

pipeline:
  - uses: fetch
    with:
      expected-sha256: 64ac4614db292ae8c5aa26de0295bf1623dbb3985054cb656c55e67431def17c
      uri: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${{package.version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libwebp-static
    pipeline:
      - uses: split/static
    description: libwebp static

  - name: libwebp-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libwebp
    description: libwebp dev

  - name: libwebp-doc
    pipeline:
      - uses: split/manpages
    description: libwebp manpages

  - name: libwebp-tools
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/* ${{targets.subpkgdir}}/usr/bin/
    description: The WebP command line tools

update:
  enabled: true
  github:
    identifier: webmproject/libwebp
    strip-prefix: v
    use-tag: true
