package:
  name: libxv
  version: 1.0.12
  epoch: 1
  description: "X11 Video extension library"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - attr-dev
      - xorgproto
      - libx11-dev
      - libxext-dev
      - util-macros

pipeline:
  - uses: fetch
    with:
      uri: https://www.x.org/releases/individual/lib/libXv-${{package.version}}.tar.xz
      expected-sha512: bdd00de1ce6a8911056181ab4de32f9e319a68567389162d4bc2e3c9946d5f3c60f87eb6c53f74c9b6a342255e591d5fef4a445a4ac8ca3c1b6fe87d42c51c1e

  - runs: |
      ./configure \
         --build=$CBUILD \
         --host=$CHOST \
         --prefix=/usr \
         --sysconfdir=/etc \
         --mandir=/usr/share/man \
         --localstatedir=/var
      make
      make DESTDIR="${{targets.destdir}}" install
      install -D -m644 COPYING "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/COPYING

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: headers for ${{package.name}}
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libxv

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: ${{package.name}} manpages

update:
  enabled: true
  release-monitor:
    identifier: 1795
