package:
  name: libxkbfile
  version: 1.1.2
  epoch: 0
  description: X11 keyboard file manipulation library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - libx11-dev
      - util-macros

pipeline:
  - uses: fetch
    with:
      expected-sha512: 0639fad7b64b36a85f8d24cdd40085e0ec18d7a671793b8b5c26449e9cc5a84c37117e7757fb1238ac353044935dd00013e42166de5af9dec428e873a47e598d
      uri: https://www.x.org/releases/individual/lib/libxkbfile-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      install -D -m644 COPYING \
      "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/COPYING

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 1781
