package:
  name: libzip
  version: 1.10.0
  epoch: 0
  description: "A C library for reading, creating, and modifying zip archives."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - zlib
      - bzip2

environment:
  contents:
    packages:
      - build-base
      - ca-certificates-bundle
      - openssl
      - busybox
      - zlib-dev
      - bzip2-dev

pipeline:
  - uses: fetch
    with:
      uri: https://libzip.org/download/libzip-${{package.version}}.tar.gz
      expected-sha256: 52a60b46182587e083b71e2b82fcaaba64dd5eb01c5b1f1bc71069a3858e40fe

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 10649
