package:
  name: mdbook
  version: 0.4.31
  epoch: 1
  description: "Create book from markdown files. Like Gitbook but implemented in Rust."
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - rust
      - libLLVM-15
      - wolfi-base
      - busybox
      - make
      - git
      - ca-certificates-bundle
      - build-base
      - openssl-dev
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rust-lang/mdbook
      tag: v${{package.version}}
      expected-commit: 904aa530b5f59387f19feb0dbe0e959de3f247d2

  - name: Configure and build
    runs: |
      cargo build --release
      install -d "${{targets.destdir}}"/usr/bin
      install -m755 target/release/mdbook "${{targets.destdir}}"/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: rust-lang/mdbook
    use-tag: true
    strip-prefix: v
