package:
  name: minio
  # minio uses strange versioning, the upstream version is RELEASE.2023-06-19T19-52-50Z
  # when bumping this, also bump the tag in git-checkout below
  version: 0.20230619.195250
  epoch: 0
  description: Multi-Cloud Object Storage
  copyright:
    - license: AGPL-3.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      # Pinned to 1.19 due to upstream issues
      - go-1.19
      - build-base
      - perl

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/minio
      tag: RELEASE.2023-06-19T19-52-50Z
      expected-commit: f9b8d1c6999e65ab31899cbbe0314f5a4e5257c3

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv minio ${{targets.destdir}}/usr/bin

update:
  enabled: false # uses strange versioning
