package:
  name: opus
  version: 1.4
  epoch: 2
  description: Codec designed for interactive speech and audio transmission over the Internet
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - meson

pipeline:
  - uses: fetch
    with:
      expected-sha512: 1ecd39e0add24de12823bf7c936bb67441228721e2cdae0edbfcf3cee0894bcc6edf2a1d0ca5cdfdad1565803bf39cc4c985ad32710c2a9582f850adeb5ca631
      uri: https://github.com/xiph/opus/releases/download/v${{package.version}}/opus-${{package.version}}.tar.gz

  - uses: patch
    with:
      # https://github.com/xiph/opus/pull/267
      patches: have_arm_intrinsics_or_asm.patch

  - runs: |
      CFLAGS="${CFLAGS/-Os/-O2}" \
      CPPFLAGS="${CPPFLAGS/-Os/-O2}" \
      meson \
         -Db_lto=true \
         -Dcustom-modes=true \
         -Dtests="$(want_check && echo enabled || echo disabled)" \
         . output
      meson compile -C output
      DESTDIR="${{targets.destdir}}" meson install --no-rebuild -C output
      install -Dm644 COPYING "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

subpackages:
  - name: ${{package.name}}-doc
    description: ${{package.name}} documentation
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    description: ${{package.name}} dev

update:
  enabled: true
  ignore-regex-patterns:
    - draft-*
    - draft-ietf*
  github:
    identifier: xiph/opus
    strip-prefix: v
    use-tag: true
