package:
  name: py3-hatchling
  version: 1.18.0
  epoch: 0
  description: "Modern, extensible Python build backend"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - python3
      - py3-installer

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/h/hatchling/hatchling-${{package.version}}-py3-none-any.whl
      expected-sha512: 2a432fcae2782a9ae5bdfff556bff7b58f6e437fc7ddebd8dac9b21f6b06a0064f9e83c05f5f89c6ab913d10ca101f0e610feb1355ec18f7a9c2f5b3e10de619
      extract: false
      delete: false

  - runs: |
      find .
      python3 -m installer -d "${{targets.destdir}}" ./hatchling-${{package.version}}-py3-none-any.whl

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 185085
