package:
  name: py3-botocore
  version: 1.29.153
  epoch: 0
  description: "The low-level, core functionality of Boto3"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-dateutil
      - py3-docutils
      - py3-jmespath
      - py3-urllib3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/b/botocore/botocore-${{package.version}}.tar.gz
      expected-sha256: d59b8e87138581a339b9f84a9e90bc4c1a152cf8ca2adbaad7792a4c4125bffa

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 29738
