package:
  name: py3.11-setuptools
  version: 68.0.0 # When bumping this, also bump the provides below!
  epoch: 0
  description: Easily download, build, install, upgrade, and uninstall Python packages
  copyright:
    - license: "MIT"
  dependencies:
    provides:
      - py3-setuptools=67.8.0
    runtime:
      - python-3.11

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - wolfi-base
      - busybox
      - build-base
      - python-3.11

pipeline:
  - uses: fetch
    with:
      expected-sha256: baf1fdb41c6da4cd2eae722e135500da913332ab3f2f5c7d33af9b492acb5235
      uri: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-${{package.version}}.tar.gz

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

update:
  enabled: true
  shared: true
  release-monitor:
    identifier: 4021
