package:
  name: regclient
  version: 0.5.0
  epoch: 0
  description: Docker and OCI Registry Client in Go and tooling using those libraries
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/regclient/regclient/archive/v${{package.version}}/v${{package.version}}.tar.gz
      expected-sha256: a80483527b80463fe532fed7ac4c8ecfa7181f3ab9bdc4170c3b2c4531c60c95

  - runs: |
      CGO_ENABLED=0 go build \
        -trimpath -ldflags "-s -w -extldflags -static -buildid=" \
        -o "${{targets.destdir}}/usr/bin/regctl" ./cmd/regctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: regclient/regclient
    strip-prefix: v
