package:
  name: swaks
  version: '20201014.0'
  epoch: 0
  description: "File archiver with a high compression ratio"
  copyright:
    - license: LGPL-2.0-only

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://www.jetmore.org/john/code/swaks/files/swaks-${{package.version}}.tar.gz
      expected-sha512: 8a4e8dc810a9c5943afdbc4db7130e110c42e211d6927ce1cdbab6f81fa49c31490e6c3668ec3cea79580c07b281ce30901b3b4a71325951167158cc9d70d9cc

  - runs: |
      install -Dm755 ${{package.name}} "${{targets.destdir}}"/usr/bin/${{package.name}}
      install -Dm644 -t "${{targets.destdir}}"/usr/share/doc/${{package.name}} doc/*

  - uses: strip

subpackages:
  - name: "${{package.name}}-doc"
    description: "${{package.name}} documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc/${{package.name}} "${{targets.subpkgdir}}"/usr/share

update:
  enabled: true
  release-monitor:
    identifier: 8862
