package:
  name: terraform
  version: 1.5.2
  epoch: 0
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/hashicorp/terraform
      tag: v${{package.version}}
      expected-commit: 447fa83f94bd8075c7d0356adf3df01f203715b1

  - uses: go/build
    with:
      packages: .
      output: terraform
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: hashicorp/terraform
    strip-prefix: v
    use-tag: true
