package:
  name: tiff
  version: 4.5.1
  epoch: 1
  description: Provides support for the Tag Image File Format or TIFF
  copyright:
    - license: libtiff

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - zlib-dev
      - libjpeg-turbo-dev
      - libwebp-dev
      - zstd-dev
      - python3
      - cmake
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 3c080867114c26edab3129644a63b708028a90514b7fe3126e38e11d24f9f88a
      uri: https://download.osgeo.org/libtiff/tiff-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: tiff-doc
    pipeline:
      - uses: split/manpages
    description: tiff manpages

  - name: tiff-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - tiff
        - zlib-dev
        - libjpeg-turbo-dev
        - libwebp-dev
        - zstd-dev
    description: tiff dev

update:
  enabled: true
  release-monitor:
    identifier: 1738
