package:
  name: wasmtime
  version: 10.0.0
  epoch: 0
  description: "A fast and secure runtime for WebAssembly"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - rust
      - libLLVM-15
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bytecodealliance/wasmtime
      tag: v${{package.version}}
      expected-commit: 205f8311aba6848184c1c76cf90c93d4ea61433e

  - name: Configure and build
    runs: |
      git submodule update --init
      cargo build --release -vv
      cargo build --release --manifest-path crates/c-api/Cargo.toml
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/wasmtime ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: "libwasmtime"
    description: "c library for wasmtime"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/
          mv target/release/libwasmtime.* ${{targets.subpkgdir}}/usr/lib/
      - uses: strip

update:
  enabled: true
  github:
    identifier: bytecodealliance/wasmtime
    strip-prefix: v
