package:
  name: weaviate
  version: 1.19.10
  epoch: 0
  description: Weaviate is an open source vector database that stores both objects and vectors, allowing for combining vector search with structured filtering with the fault-tolerance and scalability of a cloud-native database, all accessible through GraphQL, REST, and various language clients.
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/weaviate/weaviate
      tag: v${{package.version}}
      expected-commit: 7c6a2e7a73a6652dd867cd4bc29647bd4cda1dcf

  - runs: |
      mkdir -p ${{targets.destdir}}/bin
      GITHASH=$(git rev-parse --short HEAD)
      go build \
        -ldflags '-s -w -extldflags "-static" -X github.com/weaviate/weaviate/usecases/config.GitHash='"$GITHASH"'' \
        -o ${{targets.destdir}}/bin/weaviate ./cmd/weaviate-server

update:
  enabled: true
  github:
    identifier: weaviate/weaviate
    strip-prefix: v
    tag-filter: v
    use-tag: true
