name: Wolfictl Check Updates

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Get changed files
      id: files
      uses: tj-actions/changed-files@210cc839c24f532fe4fbf510b7b3314ca9a2b90b # v35.5.1
      with:
        separator: ' '
        files: "*.yaml"

    - name: Check
      id: check
      if: ${{ steps.files.outputs.all_changed_files != '' }}
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:4ee6e87bd566dce9d5743de6ce7733ea80856a0e11884fead4cc79bfd18fa7f1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: wolfictl
        args: check update ${{ steps.files.outputs.all_changed_files }}